---
title: "Immune profile analysis"
author: "García-Mulero"
date: "3/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Immune profiling of samples in dataset

Load data  
```{r}
infoClin <- read.table("data/mets_infoClin.txt", sep="\t", header=T, stringsAsFactors = F)
ex <- read.table("data/mets_expression_combat.txt", sep="\t", header=T, stringsAsFactors = F)
```

Load libraries
```{r}
library(MCPcounter); library(estimate)
```

### Run Immunophenoscore
```{r}
####################################################
##
##   This R-script can be used to calculate Immunophenoscore (IPS) and generate Immunophenogram from "EXPR.txt" and "IPS_genes.txt"
##   (C) ICBI, Medical University of Innsbruck, Biocenter, Division of Bioinformatics
##   Version 1.0 08.07.2016
##   Dependencies ggplot2,grid,gridExtra
##
####################################################
ipsmap<- function (x) {
	if (x<=0) {
		ips<-0
	} else {
		if (x>=3) {
		 ips<-10
		} else {
			ips<-round(x*10/3, digits=0)
		}
	}
	return(ips)
}
# expression data
gene_expression <- ex
sample_names<-names(gene_expression)
## Read IPS genes and corresponding weights from tab-delimited text file "IPS_genes.txt"
IPSG<-read.table("IPS_genes.txt",header=TRUE, sep="\t", dec = ".",check.names=FALSE)
unique_ips_genes<-as.vector(unique(IPSG$NAME))

##add gene values for genes not in the expression matrix
mean_values <- apply(gene_expression, 2, mean)
genes <- IPSG$GENE[!(IPSG$GENE %in% rownames(gene_expression))]
for (i in 1:length(genes)){
	gene <- genes[i]
	gene_expression[nrow(gene_expression)+1,] <- mean_values
	rownames(gene_expression)[nrow(gene_expression)] <- as.character(gene)
	i <- i+1
}
gene_expression <- gene_expression[order(rownames(gene_expression)),]

IPS<-NULL
MHC<-NULL
CP<-NULL
EC<-NULL
SC<-NULL
AZ<-NULL

for (i in 1:length(sample_names)) {
	GE<-gene_expression[[i]]
	mGE<-mean(GE)
	sGE<-sd(GE)
	Z1<-(gene_expression[as.vector(IPSG$GENE),i]-mGE)/sGE
	W1<-IPSG$WEIGHT
	WEIGHT<-NULL
	MIG<-NULL
	k<-1
	for (gen in unique_ips_genes) {
		MIG[k]<- mean(Z1[which (as.vector(IPSG$NAME)==gen)])
		WEIGHT[k]<- mean(W1[which (as.vector(IPSG$NAME)==gen)])
		k<-k+1
	}
	WG<-MIG*WEIGHT
	MHC[i]<-mean(WG[1:10])
	CP[i]<-mean(WG[11:20])
	EC[i]<-mean(WG[21:24])
	SC[i]<-mean(WG[25:26])
	AZ[i]<-sum(MHC[i],CP[i],EC[i],SC[i])
	IPS[i]<-ipsmap(AZ[i])
}
DF<-data.frame(SAMPLE=sample_names,MHC=MHC,EC=EC,SC=SC,CP=CP,AZ=AZ,IPS=IPS)
rownames(DF) <- DF$SAMPLE
DF$SAMPLE <- NULL
ips <- t(DF)

write.table(ips,file="data/IPS_scores_mets.txt",
	row.names=TRUE, col.names=TRUE, quote=FALSE,sep="\t")
```

### Run MCPcounter
```{r}
# load genes
genes <- read.table("data/MCPcounter_genes.txt", 
	sep="\t", stringsAsFactors=F, colClasses="character", header=T)
colnames(genes)[2] <- "Cell population"
colnames(genes)[1] <- "HUGO symbols"

#calculate cell populations
mcp <- MCPcounter.estimate(ex, featuresType="HUGO_symbols")



```

### Run ESTIMATE
```{r}
# save expression data
write.table(ex_comb, file="estimate/expression_mets.txt", 
  sep="\t", quote=F, col.names=TRUE, row.names=TRUE)

# filter common genes
filterCommonGenes(input.f="estimate/expression_mets.txt", 
                  output.f="estimate/expression_mets.gct", id="GeneSymbol")

#estimate
estimateScore("estimate/expression_mets.gct", "estimate/mets_estimate_scores.gct", platform="affymetrix")
est <- read.delim("estimate/mets_estimate_scores.gct", header=T, skip=2)
est <- as.data.frame(est)
est[,0:5]
rownames(est) <- est$NAME
est$Description <- NULL
est$NAME <- NULL
```
Save files
```{r}
### Join MCP_res and Estimate
identical(colnames(est), colnames(MCP_res))
mcp_res <- rbind(MCP_res,est)

### Save matrix
write.table(mcp_res, file="data/mcp_est_scores.txt",
    row.names=TRUE, col.names=TRUE, quote=FALSE,sep="\t")
```

### TIS enrichment
```{r}
# genes selected
TIS <- c("CCL5", "CD27", "CD274", "CD276", "CD8A", "CMKLR1", "CXCL9", "HLA-DQA1", "HLA-DRB1", "HLA-E", "IDO1", "LAG3", "NKG7", "PDCD1LG2", "PSMB10", "STAT1", "TIGIT")
library(GSVA)
GSVA <- gsva(expr=as.matrix(ex), 
             gset.idx.list=list(TIS), method="gsva")
GSVA <- as.data.frame(t(GSVA))
#save
write.table(GSVA, file="data/mets_tis_signature.txt", sep="\t", col.names = T, row.names = T, quote = F)
```

